name: 04-Using Actions
on: [push]
jobs:
    build-to-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing folder
              run: tree
            - name: setup node 
              uses: actions/setup-node@v4
              with: 
               node-version: '20.x'
            - name: install dependencies
              run: |
                   cd 04-using-actions/react-app
                   npm ci
              

              

